apiVersion: v1
kind: Service
metadata:
  labels:
    app: sads
  name: sads
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sads

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sads
  name: sads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sads
  template:
    metadata:
      labels:
        app: sads
    spec:
      containers:
        - image: "ghcr.io/berserkrambo/k4sme.ai4sdw.dash:main"
          imagePullPolicy: Always
          name: sads
          ports:
          - containerPort: 8000
            name: http
          env:
          - name: "STREAMLIT_SERVER_BASE_URL_PATH"
            value: "/sads"
